stages:
  - build
  - test
  - verify
  - deploy

variables:
  SONAR_ARGS: "\
  -Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} \
  -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME} \
  "

.build_pet-clinic:
  stage: build
  tags:
    - runner
  variables:
    SKIP_TEST: "false"
  script:
    - mvn clean
    - mvn package -DskipTests=${SKIP_TEST}
  artifacts:
    when: always
    expire_in: 30 day
    paths:
      - "*/target/reports"

.build_pet-clinic_doc:
  stage: build
  tags:
    - runner
  variables:
    DOCKERFILE: .GITLAB/Dockerfile
  script:
    - docker build --no-cache -t ${CI_PROJECT_NAME}/doc -f ${DOCKERFILE} .

.junit_module_test_run:
  stage: test
  tags:
    - runner
  variables:
    MODULE: ""
  script:
    - cd ${MODULE}
    - mvn test
  artifacts:
    when: always
    expire_in: 30 day
    paths:
      - "*/target/reports"

.junit_test_run:
  stage: test
  tags:
    - runner
  script:
    - mvn test
  artifacts:
    when: always
    expire_in: 30 day
    paths:
    - "*/target/reports"

.sonar_review:
  stage: verify
  tags:
    - runner
  dependencies: []
  script:
    - >
      if [ "$CI_BUILD_REF_NAME" == "main" ]; then
        mvn compile sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS
      else
        mvn compile sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS -Dsonar.analysis.mode=preview
      fi

.trigger_deploy:
  stage: deploy
  tags:
    - runner
  variables:
    URL: "https://gitlab.com/api/v4/projects/44538218/trigger/pipeline"
    POST_DATA: "\
      token=${DEPLOY_TOKEN}&\
      ref=master&\
      variables[DEPLOY]=${DEPLOY}&\
      variables[DEPLOY_CI_REPOSITORY_URL]=${CI_REPOSITORY_URL}&\
      variables[DEPLOY_CI_PROJECT_NAME]=${CI_PROJECT_NAME}&\
      variables[DEPLOY_CI_COMMIT_SHA]=${CI_COMMIT_SHA}&\
      variables[DEPLOY_CI_COMMIT_TAG]=${CI_COMMIT_TAG}
      "
  script:
  - wget --content-on-error -qO- ${URL} --post-data ${POST_DATA}

.trigger_release_deploy:
  extends: .trigger_deploy
  only:
    - tags

.trigger_snapshot_deploy:
  extends: .trigger_deploy
  when: manual
  except:
    - tags